// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMaj_Ylu1sll-INsszwHTE4DdTyRuLNa8',
    appId: '1:658116732531:web:3f69b6beae05a5d0472c06',
    messagingSenderId: '658116732531',
    projectId: 'chatterapp-3b2e4',
    authDomain: 'chatterapp-3b2e4.firebaseapp.com',
    databaseURL: 'https://chatterapp-3b2e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterapp-3b2e4.firebasestorage.app',
    measurementId: 'G-WD1H8N1H3G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0aPRwZqY_PJE-Izk-TuH18vwVAU9lCrg',
    appId: '1:658116732531:android:42bfa4db852b1e62472c06',
    messagingSenderId: '658116732531',
    projectId: 'chatterapp-3b2e4',
    databaseURL: 'https://chatterapp-3b2e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterapp-3b2e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF6XdEyOANV0Cv_j3_3DoFNasfAC4ZblM',
    appId: '1:658116732531:ios:69cbfc476f83ccc7472c06',
    messagingSenderId: '658116732531',
    projectId: 'chatterapp-3b2e4',
    databaseURL: 'https://chatterapp-3b2e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterapp-3b2e4.firebasestorage.app',
    androidClientId: '658116732531-iketqgl236uu9roonjlmdruolb5d8s7f.apps.googleusercontent.com',
    iosClientId: '658116732531-q6vhbrsbo8cp2j9hajnfs75v4cfu2k3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskCatalift',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAF6XdEyOANV0Cv_j3_3DoFNasfAC4ZblM',
    appId: '1:658116732531:ios:69cbfc476f83ccc7472c06',
    messagingSenderId: '658116732531',
    projectId: 'chatterapp-3b2e4',
    databaseURL: 'https://chatterapp-3b2e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterapp-3b2e4.firebasestorage.app',
    androidClientId: '658116732531-iketqgl236uu9roonjlmdruolb5d8s7f.apps.googleusercontent.com',
    iosClientId: '658116732531-q6vhbrsbo8cp2j9hajnfs75v4cfu2k3n.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTaskCatalift',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMaj_Ylu1sll-INsszwHTE4DdTyRuLNa8',
    appId: '1:658116732531:web:0f25759147effb4c472c06',
    messagingSenderId: '658116732531',
    projectId: 'chatterapp-3b2e4',
    authDomain: 'chatterapp-3b2e4.firebaseapp.com',
    databaseURL: 'https://chatterapp-3b2e4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'chatterapp-3b2e4.firebasestorage.app',
    measurementId: 'G-3EJNNNJ3PN',
  );
}
